### ISSUE TITLE
add get image path indexer's lookup

### ISSUE THREAD

**Issue by earthy123** [tensorflow/similarity#145]

**Comment by ebursztein** [comment]
You can add which ever data you want in the indexer including the image path. We can add this answer to the FAQ but there is no need to add something custom for the image.

**Comment by earthy123** [comment]
What about an end-to-end example of custom dataset instead of TensorFlow catalog dataset. For example dataset from Kaggle.

**Comment by owenvallis** [comment]
That's a good idea, we will be adding a new example notebook that demonstrates the Samplers and will add an example loading data from Kaggle.

The new notebook will be in the 0.14 update.

**Comment by owenvallis** [comment]
The data loader notebook is available in the examples directory, and we will be adding several new notebooks that will demonstrate using TF data.Dataset.
