### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by msafi04** [tensorflow/similarity#152]
I get the following error while importing Similarity Models, Please help me with this

Thanks

TensorFlow Version: 2.4.1
Run in Kaggle Notebook

`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_43/3853842158.py in <module>
      2 from tensorflow_similarity.layers import MetricEmbedding # row wise L2 norm
      3 from tensorflow_similarity.losses import MultiSimilarityLoss  # specialized similarity loss
----> 4 from tensorflow_similarity.models import SimilarityModel # TF model with additional features
      5 from tensorflow_similarity.samplers import MultiShotMemorySampler  # sample data
      6 from tensorflow_similarity.samplers import select_examples  # select n example per class

/opt/conda/lib/python3.7/site-packages/tensorflow_similarity/models/__init__.py in <module>
     15 functionalities to make training and serving similarity models quick and easy.
     16 """
---> 17 from .similarity_model import SimilarityModel  # noqa

/opt/conda/lib/python3.7/site-packages/tensorflow_similarity/models/similarity_model.py in <module>
     30 from tensorflow_similarity.distances import Distance
     31 from tensorflow_similarity.distances import distance_canonicalizer
---> 32 from tensorflow_similarity.training_metrics import DistanceMetric
     33 from tensorflow_similarity.evaluators.evaluator import Evaluator
     34 from tensorflow_similarity.indexer import Indexer

/opt/conda/lib/python3.7/site-packages/tensorflow_similarity/training_metrics/__init__.py in <module>
     13 # limitations under the License.
     14 "Specialized `keras.metrics` that tracks how distances evolves during training."
---> 15 from .utils import batch_class_ratio  # noqa
     16 from .distance_metrics import DistanceMetric # noqa
     17 from .distance_metrics import DistanceGapMetric # noqa

/opt/conda/lib/python3.7/site-packages/tensorflow_similarity/training_metrics/utils.py in <module>
     13 # limitations under the License.
     14 
---> 15 from tensorflow_similarity.samplers.samplers import Sampler
     16 
     17 import tensorflow as tf

/opt/conda/lib/python3.7/site-packages/tensorflow_similarity/samplers/__init__.py in <module>
     34 from .memory_samplers import SingleShotMemorySampler  # noqa
     35 from .tfrecords_samplers import TFRecordDatasetSampler  # noqa
---> 36 from .tfdataset_samplers import TFDatasetMultiShotMemorySampler  # noqa

/opt/conda/lib/python3.7/site-packages/tensorflow_similarity/samplers/tfdataset_samplers.py in <module>
     16 
     17 from tqdm.auto import tqdm
---> 18 import tensorflow_datasets as tfds
     19 
     20 from .samplers import Augmenter

/opt/conda/lib/python3.7/site-packages/tensorflow_datasets/__init__.py in <module>
     41 # needs to happen before anything else, since the imports below will try to
     42 # import tensorflow, too.
---> 43 from tensorflow_datasets.core import tf_compat
     44 tf_compat.ensure_tf_install()
     45 

/opt/conda/lib/python3.7/site-packages/tensorflow_datasets/core/__init__.py in <module>
     20 from tensorflow_datasets.core import tf_compat
     21 
---> 22 tf_compat.ensure_tf_install()
     23 
     24 # pylint:disable=g-import-not-at-top

/opt/conda/lib/python3.7/site-packages/tensorflow_datasets/core/tf_compat.py in ensure_tf_install()
     45 
     46   try:
---> 47     import tensorflow.compat.v2 as tf  # pylint: disable=import-outside-toplevel
     48   except ImportError:
     49     # Print more informative error message, then reraise.

/opt/conda/lib/python3.7/site-packages/tensorflow/_api/v2/compat/__init__.py in <module>
     37 import sys as _sys
     38 
---> 39 from . import v1
     40 from . import v2
     41 from tensorflow.python.compat.compat import forward_compatibility_horizon

/opt/conda/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/__init__.py in <module>
     32 from . import autograph
     33 from . import bitwise
---> 34 from . import compat
     35 from . import config
     36 from . import data

/opt/conda/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/compat/__init__.py in <module>
     37 import sys as _sys
     38 
---> 39 from . import v1
     40 from . import v2
     41 from tensorflow.python.compat.compat import forward_compatibility_horizon

/opt/conda/lib/python3.7/site-packages/tensorflow/_api/v2/compat/v1/compat/v1/__init__.py in <module>
    192 from tensorflow.python.framework.tensor_util import MakeNdarray as make_ndarray
    193 from tensorflow.python.framework.tensor_util import constant_value as get_static_value
--> 194 from tensorflow.python.framework.tensor_util import is_tf_type as is_tensor
    195 from tensorflow.python.framework.tensor_util import make_tensor_proto
    196 from tensorflow.python.framework.type_spec import TypeSpec

ImportError: cannot import name 'is_tf_type' from 'tensorflow.python.framework.tensor_util' (/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/tensor_util.py)`

**Comment by Rishit-dagli** [comment]
I was recently trying it out in Kaggle as well, you need TensorFlow >=2.6 for the package, if you upgrade to 2.6 in Kaggle and restart the runtime which worked for me.

**Comment by msafi04** [comment]
Thanks its works.
Need to keep the GPU on as well
