### ISSUE TITLE
how to do Indexing with tf.data.Dataset object?

### ISSUE THREAD

**Issue by msafi04** [tensorflow/similarity#153]
How do we do Indexing with dataset created using tf.data.Dataset?

Thanks

**Comment by owenvallis** [comment]
Hi,

We have an example of indexing using the TFDataset sampler in the visualizer notebook.

https://github.com/tensorflow/similarity/blob/master/examples/supervised_visualization.ipynb

We are also adding a more detailed Sampler notebook in the upcoming 0.14 release at the end of the month.

**Comment by owenvallis** [comment]
Added in 0.14 [Sampler IO Cookbook](https://github.com/tensorflow/similarity/blob/master/examples/sampler_io_cookbook.ipynb). Let us know if there are additional examples you'd like to see in the notebook.
