### ISSUE TITLE
Reporting typos in Hello World tutorial notebook

### ISSUE THREAD

**Issue by tanemaki** [tensorflow/similarity#154]
Thanks for the great work.

The Hello World tutorial notebook was very well designed and surely helpful for me to catch up to speed. Thanks :)
https://github.com/tensorflow/similarity/blob/master/examples/supervised_hello_world.ipynb

I think I found some minor typos while walking through the tutorial, so here is the list.

First, I think the point of the last section of this tutorial is to query the reloaded model. However, the model used here for the query appears to be not the reloaded model, but the original one.

I might be wrong, but  
```
# lookup the nearest neighbors
nns = model.lookup(x_display, k=num_neighboors)
```
might be
```
# lookup the nearest neighbors
nns = reloaded_model.lookup(x_display, k=num_neighboors)
```
.

Secondly, renaming some constants to match the parameter names of `MultiShotMemorySampler` might be great for a baby programmer like me ^^

```
CLASS_PER_BATCH -> CLASSES_PER_BATCH
EXAMPLE_PER_CLASS -> EXAMPLES_PER_CLASS
```

Finally, the output of this cell appears to be a bit strange and may need to be re-evaluated.
<img width="618" alt="matching" src="https://user-images.githubusercontent.com/3511941/133839848-6d513504-0533-4d11-a356-3bb5e7e58a53.png">

Best,

**Comment by owenvallis** [comment]
Thanks for taking the time to review the notebook and glad the notebook was helpful.

Regarding the typos:

* Looks like you're right, we should be calling `lookup()` on the reloaded model. I'll push a quick fix for that.
* Those are some good suggestions for updating the parameter names. We'll look at updating that as part of the bump to 0.14.0
* The table rows are correct, but it looks like we just needed to rerun the cell to get the correct header output. I'll add this as part of the reload.lookup() fix.

**Comment by owenvallis** [comment]
Pushed the updates to the Notebook.

**Comment by tanemaki** [comment]
Thanks for the update.

Regarding the second point, I didn't mean to update the parameter names (they are already good) but renaming the name of constants that are passed as arguments to `MultiShotMemorySampler`. Sorry for this confusion.

Here is the cell that defines the constants passed as arguments to `MultiShotMemorySampler`.
![スクリーンショット 2021-09-21 9 35 43](https://user-images.githubusercontent.com/3511941/134097455-ff141d53-9820-48b8-93e7-5700052c05bf.png)
and suggested modification:
```
CLASS_PER_BATCH -> CLASSES_PER_BATCH
EXAMPLE_PER_CLASS -> EXAMPLES_PER_CLASS or EXAMPLES_PER_CLASS_PER_BATCH
```

Anyway, they are very minor details, so please feel free to close this issue when you feel appropriate :)

**Comment by owenvallis** [comment]
oh, thanks for clarifying. Both the constants in the notebook and the parameter names are now updated in the 0.14 branch.

**Comment by owenvallis** [comment]
Closing this issue as the changes are now in 0.14.
