### ISSUE TITLE
Add possibility to use tf.data.Dataset API as input pipeline

### ISSUE THREAD

**Issue by alessiogatto** [tensorflow/similarity#168]
Hi, i have seen that is not possible to use tf.data.Dataset as input for a sampler. Input must be the couple img, label or a dataset loaded directly from Tensorflow catalog. It will be developed a new sampler method that accepts as input a tf.data.Dataset?

Thanks

**Comment by owenvallis** [comment]
Hi, we currently support tf.data.Dataset via the TFRecordDatasetSampler. The tricky part with using tf.data.Datsaset is ensuring that the batches consist of correct number of classes and number of examples per class. See #171 for more details on how this works. 

In summary we would like to use [choose_from_datasets](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#choose_from_datasets) but this seems to be slow when the number of datasets is large. Instead we write tf record files and use [interleave](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#interleave) instead. You can base your sampler of  TFRecordDatasetSampler  as it returns a Dataset object.
