### ISSUE TITLE
DistanceMetric - incorrect condition statement for distance update

### ISSUE THREAD

**Issue by adbelniak** [tensorflow/similarity#174]
In `distance_metrics.py` file, line 74:
For `negative_mining_strategy` = `hard`, masked are values with maximum distances.
```
    if self.negative_mining_strategy == 'easy':
        distances, _ = masked_min(pairwise_distances, negative_mask)
    else:
        distances, _ = masked_max(pairwise_distances, negative_mask)
```

I think this statement should be switched in place.

**Comment by owenvallis** [comment]
Thanks for catching the this, pushed a fix in https://github.com/tensorflow/similarity/commit/eeb9c69d529854e9ce4388d65399b80b466b6371
