### ISSUE TITLE
loading a model in a new python session doesn't work as expected

### ISSUE THREAD

**Issue by noa-loewenthal** [tensorflow/similarity#188]
I'm building a model following the [hello_world](https://github.com/tensorflow/similarity/blob/master/examples/supervised_hello_world.ipynb) notebook. Everything works well as long as I'm in the same python session. Once I try to load the model in a different session, the loaded object it no longer an instance of `tensorflow_similarity.models.similarity_model.SimilarityModel` but rather of `tensorflow.python.keras.engine.functional.Functional` so loading the index fails.
I found a workaround that I don't understand why works:  creating an instance of `SimilarityModel` (the parameters don't matter) in my new python session, makes the index loading to work.

So in the **first session** I save my model:
```
save_path = 'models/hello_world' 
model.save(save_path)
```
In the **second session**, if I run:
```
save_path = 'models/hello_world'
reloaded_model = load_model(save_path)
reloaded_model.load_index(save_path)
```
I get `AttributeError: 'Functional' object has no attribute 'load_index'`.
**But**, if in the **second session** I run:
```
dummy_model = SimilarityModel(layers.Input(1), layers.Input(1))
save_path = 'models/hello_world'
reloaded_model = load_model(save_path)
reloaded_model.load_index(save_path)
```
everything works perfectly.

**Comment by owenvallis** [comment]
I think this is because the SimilarityModel is a custom object. One way to address this is the following:

```
import tensorflow as tf
import tensorflow_similarity as tfsim

save_path = 'models/hello_world'
model = tf.keras.models.load_model(
    save_path, 
    custom_objects={'SimilarityModel': tfsim.models.SimilarityModel}),
)
model.load_index(save_path)
```
