### ISSUE TITLE
Dangerous misguide

### ISSUE THREAD

**Issue by Primadual** [tensorflow/similarity#190]
So I just followed your "instruction" by typing in "pip install tensorflow_similarity" and that REMOVED MY CURRENT TF INSTALLATION and installed version 2.7! You should have put a warning there what happens if we use your so called professional guide! Very unimpressed by this. Please put in a RED MARK there and explain it will DESTROY YOUR INSTALLATION of TF!

**Comment by jlarmstrongiv** [comment]
Try [virtual environments](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/#creating-a-virtual-environment), they are best practice.

**Comment by Lunatik00** [comment]
i mean, it is not expected to publish every requirement, there is no package that specifies that they have only certain version in their dependencies, if you have a requirement like that you have to use virtual environments or docker to isolate your projects or make sure that the versions that you need for everything are compatible, for your own sanity, just use virtual environments if your projects are small or personal or docker if you need to deploy them in multiple computers afterwards.

**Comment by owenvallis** [comment]
I can sympathize that clobbering your python packages is no fun, but I agree the above statements that Virtual Environments are the best practice in this case. 

Alternatively, you can always run `pip install --no-deps some_package`, but I think that depends on you version of tensorflow as tensorflow similarity depends on 2.4 or later and doesn't work with the earlier versions.
