### ISSUE TITLE
Add num repeats param to TFRecordDatasetSampler

### ISSUE THREAD

**Issue by owenvallis** [tensorflow/similarity#194]
Currently the TFRecordDatasetSampler adds a repeat after the [deserialization](https://github.com/tensorflow/similarity/blob/bb6b0fb26b4c0e41d5011ba22de5f7e4594f165d/tensorflow_similarity/samplers/tfrecords_samplers.py#L130). We will add a num_repeats param to support setting a finite number of repeats on the dataset.

See #171

**Comment by hanneshapke** [comment]
@owenvallis I think we can close this issue with the merge of #196.

**Comment by owenvallis** [comment]
sg, thanks again for the PR.
