### ISSUE TITLE
tensorflow/similarity vs image classification

### ISSUE THREAD

**Issue by DanilZittser** [tensorflow/similarity#204]
Greetings!

I don't quite understand how the tf/similarity differs from the image classification? Can I use tf/similarity without indexing to get only embeddings? 

If I do as described [here](https://github.com/tensorflow/similarity/issues/189), do I need an indexing step after training the model?

I would like to use tf/similarity for training a model of reidentification of persons like [this](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/intel/person-reidentification-retail-0286).

**Comment by owenvallis** [comment]
Hi,

TF Sim is meant to train an embedding layer using similarity and a valid metric distance. The embedding layer can then be fed to a classification layer or can be used for other things like clustering or nearest neighbor (NN) lookup.

You don't need to use the indexing features in the SimilarityModel, they just make it easier to do NN lookup.

Regarding getting the distance between two samples, you also don't need to do indexing for that. All you need is to call predict() on the two examples you would like to compare, and then measure the distance between the two resulting tensors using the same distance that you trained the model with, e.g., 'cosine' or 'euclidian'.

If you're not sure which distance you used, you can retrieve the distance function you used in your model by calling your_model._index.distance().
