### ISSUE TITLE
Augmenter on MultiShotMemorySampler

### ISSUE THREAD

**Issue by YetkinMesutKaraman** [tensorflow/similarity#206]
I couldn't apply an augmentation by using the MultiShotMemorySampler. Could someone give an example on it? Thanks

**Comment by owenvallis** [comment]
Hi,

The MultiSHotMemorySampler expects a Callable for the augmenter with the following signature:

`def augmenter(x: Tensor, y: Tensor,  num_augmentations_per_example: int, is_warmup: bool) -> List[Tensor]`

A basic augmenter might look something like the following:

```
@tf.function
def my_aug(x, y, num_augmentations_per_example, is_warmup):
    # not using this here
    del  num_augmentations_per_example
    
    if not is_warmup:
        x = tf.keras.layers.Rescaling(scale=127.0, offset=-1.0)(x)
    return x, y

sampler = tfsim.samplers. MultiShotMemorySampler(x_train, y_train, augmenter=my_aug)
```

**Comment by BakhtawarRehman** [comment]
I am having problems using an augmenter with MultiShotMemorySampler. Here is an example:

I have defined an augmenter like this:
`@tf.function
def my_aug(x, y, num_augmentations_per_example, is_warmup):
  num_augmentations_per_example = 6
  if not is_warmup:
    x = tf.keras.layers.Rescaling(scale=1./255, offset=-1.0)(x)
    x = tf.keras.layers.RandomFlip("horizontal_and_vertical")(x)
    x = tf.keras.layers.RandomRotation(0.2)(x)
    x = tf.keras.layers.RandomZoom(height_factor=(.05), width_factor=(.05))(x)
    x = tf.keras.layers.RandomContrast(0.2)(x)

  return x, y`

called it in the sampler as:
`sampler = tfsim.samplers.MultiShotMemorySampler(
    x_train,
    y_train,
    augmenter= my_aug(x_train, y_train,8,False),
    classes_per_batch=CLASSES_PER_BATCH,
    examples_per_class_per_batch=EXAMPLES_PER_CLASS,
    class_list=CLASSES[:NUM_CLASSES], 
    steps_per_epoch=STEPS_PER_EPOCH,
)`

However, when i try to 

> model.fit(sampler, epochs=EPOCHS,  validation_data=(x_test, y_test))

It gives me an error: 
`TypeError                                 Traceback (most recent call last)
[<ipython-input-98-50a1503ee0d8>](https://localhost:8080/#) in <module>
      1 EPOCHS = 5  # @param {type:"integer"}
----> 2 history = model.fit(sampler, epochs=EPOCHS,  validation_data=(x_test, y_test))

2 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow_similarity/samplers/samplers.py](https://localhost:8080/#) in generate_batch(self, batch_id)
    148 
    149         if self.augmenter:
--> 150             x, y = self.augmenter(x, y, self.num_augmentations_per_example, self.is_warmup)
    151         return x, y

TypeError: 'tuple' object is not callable`

The above error shows that i am receiving error from **"samplers.py"** and not from **"memory_samplers.py"**. I am not sure how to resolve it. Help Please!. Thanks.
