### ISSUE TITLE
error in tensorflow version check during pip install 

### ISSUE THREAD

**Issue by Lunatik00** [tensorflow/similarity#207]
I am ussing the docker rocm/tensorflow:rocm3.10-tf2.4-rc3-dev because it was the only way i could make for tensorflow to work in my rx580 since the newer rocm 4 versions are not officially compatible, so, this works with my gpu and has tensorflow 2.4, since tensorflow gpu has the requirement of tensorflow >= 2.4 it should work, but when I did the pip install it uninstalled the tensorflow 2.4 and installed 2.6 instead, which seeks for cuda libraries that i obviously don't use, there is any way for it to correctly detect that it already has tensorflow 2.4 installed so it doesn't try to use a version that is incompatible with my card? 
The package tensorflow-rocm doesnt works

![image](https://user-images.githubusercontent.com/72462823/147041634-7f17e681-4783-468f-a3ce-de578c2f35eb.png)
![image](https://user-images.githubusercontent.com/72462823/147041706-1e785ea0-1487-4b5c-8056-a7513527f9ff.png)
![image](https://user-images.githubusercontent.com/72462823/147041933-577d9ac3-a7af-4ab7-ab4f-1cb5f207886e.png)
![image](https://user-images.githubusercontent.com/72462823/147042041-40ba2cb8-c019-4d3d-b367-408f14d8dbbf.png)

I already tried specifying the tensorflow package that is installed 
![image](https://user-images.githubusercontent.com/72462823/147042571-557ef0a2-6d1b-4263-abac-693e674dc813.png)
As you can see, it is installed the 2.4.0-rc4 but apparently that doesn't count as >=2.4

**Comment by owenvallis** [comment]
Hi, I moved the tensorflow dep to extras_require. Seems like this is a common pattern to avoid tensorflow install issues.

Please let me know if this fixes the issue.

Best,

**Comment by Lunatik00** [comment]
> Hi, I moved the tensorflow dep to extras_require. Seems like this is a common pattern to avoid tensorflow install issues.
> 
> tensorflow_similarity 0.14.9 contains the fix. Please let me know if this resolves the issue.
> 
> Best,

Hi, it worked perfectly, thank you, I wont need to do workarounds to use my card and i can use the docker directly now
