### ISSUE TITLE
Bug: MetricEmbedding layer does not take name as argument?

### ISSUE THREAD

**Issue by kechan** [tensorflow/similarity#209]
TensorFlow Similarity 0.14.9
from tensorflow_similarity.layers import MetricEmbedding

In my model, I did:

    output = MetricEmbedding(metric_dim, name='metric_embedding')(x)

Got:

   TypeError: __init__() got an unexpected keyword argument 'name'

I think it is conventional for tf.keras layers to take name as argument, so you access them by calling that name (as part of the compute graph).

**Comment by owenvallis** [comment]
Hi,

You're correct. I've fixed this in the development branch as part of the 0.15 update. Let me know if you can switch to using the development branch for now, otherwise I can push a patch to the master branch.

**Comment by kechan** [comment]
@owenvallis Thanks. I don't need it urgently now, as I have not seen other problems associated with it. I just sort of did it sticking to best practice.

**Comment by owenvallis** [comment]
Sounds good and thanks for bringing it to our attention. We want to make sure we catch any these issues as they pop up.
