### ISSUE TITLE
EfficientNetSim default config cause INVALID_ARGUMENT exception for TPU

### ISSUE THREAD

**Issue by kechan** [tensorflow/similarity#218]
A prominent message is like:

```
InvalidArgumentError: 9 root error(s) found.
[[{{node similarity_model_1/sequential/random_flip/stateless_random_flip_left_right/stateless_random_uniform/StatelessRandomUniformV2}}]]
etc,
```

This is a known issue TPU can't handle many tf data augmentation layer (such as RandomCrop), so this issue is really a TPU specific one. As workaround, don't use the data augmentation that comes with EfficientNetSim:

```
with tpu_strategy.scope():
    model = EfficientNetSim((img_height, img_width, 3), 
                        embedding_size, 
                        augmentation=None, 
                        )
```
And perform data augmentation as part of your tf.data.Dataset pipeline instead: (e.g.

```
random_flip = tf.keras.layers.RandomFlip('horizontal')
train_ds = train_ds.map(lambda x, y: (random_flip(x, training=True), y), num_parallel_calls=AUTO)
```

Note that TFRecordDatasetSampler(...) returns a tf.data.Dataset object.

**Comment by owenvallis** [comment]
We just pushed 0.15 to the main branch and we decided to remove the augmentation args from all the tfsim.architectures. This is a breaking change but should resolve these issues.

**Comment by kechan** [comment]
Things are well if no augmentation layer is used in the model. Closing this issue.

Note: The TPU issue related to unimplemented op for many data augmentation keras layer is a very long standing issue, as far as I know, its been around ~2+ yrs.
