### ISSUE TITLE
Wrong argument "store_data" in documentation of SimilarityModel.index()

### ISSUE THREAD

**Issue by piebro** [tensorflow/similarity#241]
The method index() from SimilarityModel uses "data" as an argument in the [code](https://github.com/tensorflow/similarity/blob/master/tensorflow_similarity/models/similarity_model.py#L316-L358), but "store_data" is described in the [documentation](https://github.com/tensorflow/similarity/blob/master/api/TFSimilarity/callbacks/SimilarityModel.md#index).

**Comment by owenvallis** [comment]
Thanks for catching this, fix pushed to master in 6e166711f6774a34cc8c7f4d1a7280d4fed6efb8
