### ISSUE TITLE
Running similarity on multiple GPUs -  RuntimeError: `merge_call` called while defining a new graph or a tf.function.

### ISSUE THREAD

**Issue by BenSpex** [tensorflow/similarity#245]
When using the MirroredStrategy to run the similarity on multpile GPUs in my case 2 Titan RTX: 

I receive the following error: 

>

    File "/home/ben/PycharmProjects/ML/noinherit-venv/lib/python3.8/site-packages/keras/engine/training.py", line 1021, in train_function  *
        return step_function(self, iterator)
    File "/home/ben/PycharmProjects/ML/noinherit-venv/lib/python3.8/site-packages/tensorflow_similarity/models/contrastive_model.py", line 328, in train_step  *
        self.optimizer.apply_gradients(zip(gradients, tvars))
    File "/home/ben/PycharmProjects/M/noinherit-venv/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py", line 668, in apply_gradients  **
        grads_and_vars = self._aggregate_gradients(grads_and_vars)
    File "/home/ben/PycharmProjects/M/noinherit-venv/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py", line 484, in _aggregate_gradients
        return self.gradient_aggregator(grads_and_vars)
    File "/home/ben/PycharmProjects/ML/noinherit-venv/lib/python3.8/site-packages/keras/optimizer_v2/utils.py", line 39, in all_reduce_sum_gradients
        reduced = tf.distribute.get_replica_context().merge_call(

    RuntimeError: `merge_call` called while defining a new graph or a tf.function. This can often happen if the function `fn` passed to `strategy.run()` contains a nested `@tf.function`, and the nested `@tf.function` contains a synchronization point, such as aggregating gradients (e.g, optimizer.apply_gradients), or if the function `fn` uses a control flow statement which contains a synchronization point in the body. Such behaviors are not yet supported. Instead, please avoid nested `tf.function`s or control flow statements that may potentially cross a synchronization boundary, for example, wrap the `fn` passed to `strategy.run` or the entire `strategy.run` inside a `tf.function` or move the control flow out of `fn`. If you are subclassing a `tf.keras.Model`, please avoid decorating overridden methods `test_step` and `train_step` in `tf.function`.
    
 
It does not look like it would be an easy thing to fix. Any Ideas?

Thanks
Ben

**Comment by BenSpex** [comment]
UpDate: 

Removing the @tf.function decorate from the train and test step solved the problem. 
But I am not sure if this is intended

**Comment by owenvallis** [comment]
Thanks for raising this issue. We had added the tf.function decorators to help performance, but it looks like we can't add them there. Likely due to the conditionals inside the methods. I'll push a fix this week.

**Comment by BenSpex** [comment]
Hi @owenvallis 
Thanks, if you want me to help debug this let me know. Without the decorators it works like a charm even on 4 GPUs. 
I believe it is a problem of being a nested @tf.function . However I did not spend anytime to really dig deep, where the nested part comes from. 
I have a local pull on my machine and am happy to have a quick try or even performance checks if this is helpful.

**Comment by owenvallis** [comment]
Ran some tests and it looks like removing the tf.function decorator didn't impact the performance during training. Pushed a fix. Thanks again for raising the issue.

**Comment by BenSpex** [comment]
Hi @owenvallis sure. Thanks for the super quick fix. And also for the awesome repository in general.
