### ISSUE TITLE
High GPU memory usage after import

### ISSUE THREAD

**Issue by timoooo** [tensorflow/similarity#265]
Hi,
After importing the _tfsim_ in my Jupyter Notebook it instantly creates a nameless process that consumes 9967MiB on the GPU. Hence it quickly runs OOM when trying to train something. This happens only on my JupyterHub instance and not when I test it on Google Colab for example. 
```
OS: CentOS 7
Driver version: 510.47.03
Cuda version: 11.6
TF version: tested on 2.9.1 and 2.8.0
TFsim version: 0.16.2
```
Any ideas? 
![image](https://user-images.githubusercontent.com/15030831/172862834-8d669208-62bc-49ef-99a1-e4539b072573.png)

**Comment by owenvallis** [comment]
Thanks for catching this. I'm not sure what is causing this yet, but I can repro it on JupyterHub using Conda. I'll see if I can identify the import that is causing the issue.

**Comment by owenvallis** [comment]
We just pushed a patch that should fix this. Thanks again for catching this.
