### ISSUE TITLE
tfsim.visualization.projector fails with bokeh 3.0.0+

### ISSUE THREAD

**Issue by peter-doggart** [tensorflow/similarity#306]
There is a small bug that causes `tfsim.visualization.projector` to fail if bokeh 3.0.0 or above is installed. The error is:

> AttributeError: unexpected attribute 'plot_width' to figure, similar attributes are outer_width, width or min_width.

There was a breaking change in bokeh 3.0.0 major version which removed the `plot_width` and `plot_height` attributes from `figure`: https://github.com/bokeh/bokeh/issues/12543#issuecomment-1300970727 

`plot_width` and `plot_height` were just aliases for `width` and `height` as far as I can see in the 2.x series, so I think the only change required is a small update [here](https://github.com/tensorflow/similarity/blob/master/tensorflow_similarity/visualization/projector.py#L186):
```python
fig = figure(
    tooltips=tooltips,
    width=plot_size,
    height=plot_size,
    active_drag=active_drag,
    active_scroll="wheel_zoom",
)
```

**Comment by owenvallis** [comment]
Hi Peter, this is fixed in the Development branch. Let me cherry pick the change and merge it into master.
