### ISSUE TITLE
[Typo] Lables instead of labels

### ISSUE THREAD

**Issue by Lunatik00** [tensorflow/similarity#333]
in tensorflow_similarity/stores/memory_store.py there is a typo in the line 204
'''
        data = {
            "embeddings": self.embeddings[:num_records],
            "data": self.data[:num_records],
            "lables": self.labels[:num_records],
        }
'''

the string says lables instead of labels.

I decided to just report it instead of modifying the file because it might break functionality of a saved index.

**Comment by owenvallis** [comment]
Thanks for catching this. I pushed fixes as this was only in the to_dataframe method and shouldn't break any of the saved indexes.
