### ISSUE TITLE
Error with multishotfilesampler

### ISSUE THREAD

**Issue by Lunatik00** [tensorflow/similarity#341]
Hi, tere is an error with the multishot filesampler, when you have images of different sizes it should be resized so all images have the same size, otherwise many models can't use the data, or it will fail when trying to convert to a tensor in the line 196 in multishotmemorysample (https://github.com/tensorflow/similarity/blob/81d5e00033344ec6b218fc97e6e7a3c5a74ae323/tensorflow_similarity/samplers/memory_samplers.py#L196), the problem is that there isn't a way to add the target size when using the class, I think the load_image function should be inside the class and it should use a self.target_size variable from the init function

**Comment by owenvallis** [comment]
I think you can use the load_fn to resize the image before we get to the convert_to_tensor call. We set up a version of the multishot sampler for images to do just this -> tensorflow_similarity/samplers/file_samplers.py

A similar use case is doing random crops and resize to the same size. We actually have a function in our augmenters to handle doing this as well. 

Let me know that unblocks the issue. Alternatively, I also recently added a new tf.data.dataset sampler if you'd prefer to use the standard TF dataset api. tensorflow_similarity/samplers/tfdata_sampler.py

**Comment by owenvallis** [comment]
I see. The original intention was to parameterize the load function before passing it to the multishot sampler. Something like the following:

```
...
import functools

f = functools.partial(load_image, target_size=(24,24,3))

s = MultiShotFileSampler(
        x,
        y,
        load_example_fn=f,
    )
```

Or write a custom function and include the parameters inside... However, I see the issue you mentioned in the current implementation. We use the load_image func as the default and that doesn't currently provide a default target_size so it's skipped by default. That works but is probably not the most intuitive.

**Comment by Lunatik00** [comment]
ok, I didn't knew that way to use the image, is weird for how the class is made class but very useful for the MultiShotMemorySampler, since the MultiShotFileSampler is currently just the MultiShotMemorySampler with the load_image function by default. Thanks, I learned something very useful, still, when I get the time I will propose what I think will be more natural to use as a different class, my current code is not useful for this project because I use opencv to load every extension i need (mostly because the decode_images function of tensorflow doesn't load webp)
