### ISSUE TITLE
Implement SNR distance

### ISSUE THREAD

**Issue by ebursztein** [tensorflow/similarity#64]
Signal-to-Noise Ratio: A Robust Distance Metric for Deep Metric Learning   https://openaccess.thecvf.com/content_CVPR_2019/papers/Yuan_Signal-To-Noise_Ratio_A_Robust_Distance_Metric_for_Deep_Metric_Learning_CVPR_2019_paper.pdf

**Comment by Rishit-dagli** [comment]
Hi @ebursztein ,
I just came across this repo, first off loved the package! I would love to contribute this, could I take this up?
